// Ciudades y municipios de Colombia más comunes, priorizando las zonas
// típicamente más afectadas por sismos (eje cafetero, Bogotá, Santander,
// costa Caribe, etc). El campo de ciudad en los formularios es de texto
// libre con esta lista como sugerencia (datalist), así que cualquier
// municipio no listado también se puede escribir.
export const CIUDADES_COLOMBIA = [
  "Bogotá",
  "Medellín",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Cúcuta",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Armenia",
  "Ibagué",
  "Santa Marta",
  "Villavicencio",
  "Pasto",
  "Montería",
  "Neiva",
  "Popayán",
  "Valledupar",
  "Sincelejo",
  "Tunja",
  "Riohacha",
  "Quibdó",
  "Yopal",
  "Florencia",
  "San Andrés",
  "Leticia",
  "Mocoa",
  "Arauca",
  "Puerto Carreño",
  "Inírida",
  "San José del Guaviare",
  "Mitú",
  "Soacha",
  "Soledad",
  "Envigado",
  "Itagüí",
  "Bello",
  "Dosquebradas",
  "Palmira",
  "Buenaventura",
  "Girardot",
  "Chía",
  "Zipaquirá",
  "Facatativá",
  "Rionegro",
  "Apartadó",
  "Turbo",
  "Chiquinquirá",
  "Duitama",
  "Sogamoso",
  "Girón",
  "Piedecuesta",
  "Floridablanca",
  "Barrancabermeja",
  "Ocaña",
  "Pitalito",
  "Espinal",
  "Fusagasugá",
  "La Dorada",
  "Sevilla",
  "Cartago",
  "Tuluá",
  "Buga",
  "Ipiales",
  "Tumaco",
  "Magangué",
  "Ciénaga",
].sort((a, b) => a.localeCompare(b, "es"));
